#!/bin/bash

mkdir /home/jovyan/supervisor/
/usr/bin/supervisord -c /home/jovyan/supervisord.conf

export TEST = 'test'
TEST1='test'

/usr/bin/env TEST2="TEST2"

/usr/bin/env TEST3="TEST3" ${*}

exec "$@"